Repository frigid-lynx/Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#6 Create HeapSort.java
  HeapSort.java
Labels: Hactoberfest

#5 Create BinomialHeap.java
  BinomialHeap.java
Labels: Hactoberfest

#4 Create RecursiveBubbleSort.java
  RecursiveBubbleSort.java
Labels: Hactoberfest

#39 NKnight DSA Problem
  nKnight.java
Labels: Hacktoberfest-Accepted, Hacktoberfest

#38 Reverse String in java
  Reverse_string.java
Labels: Hacktoberfest-Accepted, Hacktoberfest

#37 Fibonacci Number
  Fibonacci_number
Labels: Hacktoberfest-Accepted, Hacktoberfest

#36 Java code to print triangular pattern
  Triangle_pattern.java
Labels: Hacktoberfest-Accepted, Hacktoberfest

#35 N Queen Problem
  N_Queen_Backtracking.java
Labels: Hacktoberfest-Accepted, Hacktoberfest

#46 Kadane's_algo.java
  Kadane's_algo.java
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest

#45 Add files via upload
  Reversedstring.java
  reverseastackusingrecursion.cpp
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest

#44 Simple Subtraction of numbers using java
  subtract.java
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest
